on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test-concurrency:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ format('ci-{0}-{1}', github.ref, github.actor) }}
      cancel-in-progress: true
