on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  
  test-concurrency:
    runs-on: ubuntu-latest
concurrency:
  # Feature branch builds from the same user are auto-cancelled when a trigger is received
  group: ${{ format('ci-{0}-{1}', github.ref, github.actor) }}
  cancel-in-progress: true
