on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test-concurrency:
    name: Concurrency test
    runs-on: ubuntu-latest
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
